# Generated by Django 4.0.6 on 2022-07-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='p_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
