# Generated by Django 4.0.6 on 2022-07-30 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_products_p_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pcategories',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['id'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='pcategories',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='products',
            name='balance',
            field=models.IntegerField(verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='products',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.pcategories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='products',
            name='coast',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='products',
            name='factory',
            field=models.CharField(max_length=250, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_text',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
