# Generated by Django 4.0.6 on 2022-08-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_pcategories_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
