# Generated by Django 4.0.6 on 2022-08-04 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_orderitems_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='addres',
            new_name='address',
        ),
    ]
