# Generated by Django 4.0.6 on 2022-08-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='media/prod_none.png', null=True, upload_to='media/', verbose_name='Изображение'),
        ),
    ]
